id: rails-database-config

info:
  name: Ruby-on-Rails Database Configuration Exposure
  author: pdteam
  severity: low
  tags: config,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/config/database.yml"
    matchers:
      - type: word
        words:
          - "adapter:"
          - "database:"
        condition: and
        part: body